//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owner
    {
        public Owner()
        {
            this.Animals = new HashSet<Animal>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Surname { get; set; }
        public string Forename { get; set; }
        public Nullable<System.DateTime> Date_Sold { get; set; }
    
        public virtual ICollection<Animal> Animals { get; set; }
    }
}
